describe('This is a test for cross browser tesing', () => {
    beforeEach('passes', () => {
        cy.visit('https://demoqa.com/')
        cy.viewport(1280, 720);
      })
    
    it('Practice Form', () => {
        cy.get('.category-cards > :nth-child(2)').click()
        cy.get(':nth-child(2) > .element-list > .menu-list > #item-0').click()
        cy.get('#firstName').type('Christopher')
        cy.get('#lastName').type('Owusu')
        cy.get('#userEmail').type('chrOwn@gmail.com')
        cy.get('#genterWrapper > .col-md-9 > :nth-child(1) > .custom-control-label').click()
        cy.get('#userNumber').type('0503111449')
        cy.get('#dateOfBirthInput').click()
        cy.get('.react-datepicker__month-select').select(9).invoke("val").should("eq", "9")
        cy.get('.react-datepicker__year-select').select('2000').invoke("val").should("eq", "2000")
        cy.get('.react-datepicker__week').contains('div', '20').click()
        cy.get('#dateOfBirthInput').should('have.value', '20 Oct 2000')
        cy.get('.subjects-auto-complete__value-container').click().type('c')
        cy.contains('Chemistry').click()
        cy.get('.subjects-auto-complete__value-container').click().type('ci')
        cy.contains('Civics').click()
        cy.get('.subjects-auto-complete__value-container').click().type('c')
        cy.contains('Commerce').click()
        // cy.get('.subjects-auto-complete__value-container').click().type('m')
        // cy.contains('Maths').click()
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(1) > .custom-control-label').click()
        cy.get('#hobbiesWrapper > .col-md-9 > :nth-child(3) > .custom-control-label').click()
        cy.get('#uploadPicture').attachFile('simpsons.webp')
        cy.get('#currentAddress').type('Ashiaman - Accra')
        // cy.get('#stateCity-wrapper > :nth-child(2)').click().contains('Haryana').click()
        // cy.get('#stateCity-wrapper > :nth-child(3)').click().contains('Panipat').click()
        // cy.get('#submit').click()
      })
})